
services:
  ### Posgres database for Inventory

  ### Posgres database for Products
  db-products:
    container_name: db-products
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: imagina
      POSTGRES_PASSWORD: Test123
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### Posgres database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: imagina
      POSTGRES_PASSWORD: Test123
    ports:
      - 5434:5434
    expose:
      - 5434
    command: -p 5434

  ### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5434
      DB_USER: imagina
      DB_PASSWORD: Test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181