
services:
  ### Posgres database for Inventory

  ### Posgres database for Products
  db-products:
    container_name: db-products
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: imagina
      POSTGRES_PASSWORD: Test123
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

